hmLoadTopic({
hmKeywords:"",
hmTitle:"Empfehlung: Vermeiden Sie die parallele Pflege von Artefakten in verschiedenen Systemen",
hmDescription:"TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published output files. This is a...",
hmPrevLink:"fs_7694303fb9e3.html",
hmNextLink:"fs_8c4e9fbfe746.html",
hmParentLink:"fs_0f91786ea1d0.html",
hmBreadCrumbs:"<a href=\"index.html\">Hintergründe zum TRMS<\/a> &gt; <a href=\"fs_0f91786ea1d0.html\">Zusammenspiel von IKAROS und TRMS<\/a>",
hmTitlePath:"Hintergründe zum TRMS > Zusammenspiel von IKAROS und TRMS > Empfehlung: Vermeiden Sie die parallele Pflege von Artefakten in verschiedenen Systemen",
hmHeader:"<h1 class=\"p_Heading1\" style=\"page-break-inside: avoid;\"><span class=\"f_Heading1\">Empfehlung: Vermeiden Sie die parallele Pflege von Artefakten in verschiedenen Systemen<\/span><\/h1>\n\r",
hmBody:"<p class=\"p_Normal\" style=\"page-break-inside: avoid;\">TEXT SCRAMBLING in TRIAL VERSION OUTPUT! In evaluation mode, Help+Manual will scramble individual characters in random words in your published output files. This is a limitation of the free trial version. <a href=\"https:\/\/www.helpandmanual.com\" target=\"_blank\" class=\"weblink\"> This help system was created with an evaluation copy of Help+Manual.<\/a><\/p>\n\r<hr style=\"height:2px; color:#FF0000; border-width:0; background-color:#ff0000;\" \/><p class=\"p_Normal\" style=\"page-break-inside: avoid;\">&nbsp;<\/p>\n\r<p class=\"p_Normal\" style=\"page-break-inside: avoid;\">Falls es im Zielsystem bereits ein Artefakt gibt, das denselben sprechenden Schlüssel (z. B. Vorgangsvorlagenkürzel „ABC“), aber eine andere GUID hat (oder umgekehrt), kann die Erkennung schon vorhandener Artefakte nicht korrekt funktionieren. Es kann dann zu unerwünschten Ergebnissen kommen (fälschlicherweise überschreiben oder widererwartend nicht überschreiben, sondern neu anlegen).<\/p>\n\r<p class=\"p_Normal\" style=\"page-break-inside: avoid;\">Solche Situationen können auftreten, wenn Artefakte im Zielsystem durch manuelle Anlage „nachgebaut“ oder transportierte Artefakte im Zielsystem grundlegend geändert wurden.<\/p>\n\r<p class=\"p_Normal\" style=\"page-break-inside: avoid;\"><span class=\"f_Strong\">Ferber-Software rät deshalb dringend davon ab<\/span>, in den Zielsystemen Artefakte manuell „nachzubauen“ oder identifizierende Merkmale (wie Kürzel) zu ändern, wenn die gleichen Artefakte eventuell später (erneut) aus einem TRMS in das System transportiert werden sollen. Diese Artefakte sollten ausschließlich und einheitlich über das TRMS ihren Weg in die Zielsysteme finden.<\/p>\n\r<p class=\"p_Normal\" style=\"page-break-inside: avoid;\"><span class=\"f_Strong\">Ferber-Software empfiehlt grundsätzlich<\/span>, dass Artefakte insbesondere in der <span class=\"f_Strong\">PROD<\/span>-Umgebung von IKAROS <span class=\"f_Strong\">niemals<\/span> manuell angelegt werden sollen. Neue Artefakte sollten immer in ENTW- oder INTE-Umgebungen entwickelt und getestet und dann fertig in die PROD-Umgebung transportiert (und dort nicht verändert) werden.<\/p>\n\r"
})
